name: Automated IOC enrichment & AI Analysis
on: [push]
jobs:
  ioce_enrichment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run main
        env:
          ABUSEIPDB_API_KEY: ${{ vars.ABUSEIPDB_API_KEY }}
          ALIENVAULT_API_KEY: ${{ vars.ALIENVAULT_API_KEY }}
          GEMINI_API_KEY: ${{ vars.GEMINI_API_KEY }}
          HYRID_ANALYSIS_API_KEY: ${{ vars.HYRID_ANALYSIS_API_KEY }}
          VIRUSTOTAL_API_KEY: ${{ vars.VIRUSTOTAL_API_KEY }}
        run: python main.py
