name: Configures runner as an MCP client to locally test MCP server
on:
  workflow_dispatch:
    inputs:
      ioc:
        description: "IP, domain, URL, or hash to check"
        required: true
        type: string

jobs:
  mcp_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run MCP client script to test MCP server
        env:
          IOC: ${{ github.event.inputs.ioc }}
          ABUSEIPDB_API_KEY: ${{ vars.ABUSEIPDB_API_KEY }}
          ALIENVAULT_API_KEY: ${{ vars.ALIENVAULT_API_KEY }}
          GEMINI_API_KEY: ${{ vars.GEMINI_API_KEY }}
          HYBRID_ANALYSIS_API_KEY: ${{ vars.HYBRID_ANALYSIS_API_KEY }}
          VIRUSTOTAL_API_KEY: ${{ vars.VIRUSTOTAL_API_KEY }}
          THREATFOX_ABUSE_API_KEY: ${{ vars.THREATFOX_ABUSE_API_KEY }}
        run: python gemini_mcp_client.py
